name: Build and Deploy on Fly.io

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                node-version: "20.9.0"

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Use Fly io
              uses: superfly/flyctl-actions/setup-flyctl@master
              with:
                version: 0.2.55

            - name: Deploy to Fly hosting
              run: flyctl deploy
              env:
                FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}